# Copyright (C) 2024 Inuvika Inc.
# https://www.inuvika.com
# Author David PHAM-VAN <d.phamvan@inuvika.com> 2024
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add the OS specific variables
  include_vars: "{{ item }}"
  loop:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
  failed_when: false
  tags: [ovd]

- name: Configure Apache Security headers
  when: ovd_add_security_headers
  tags: [ovd]
  lineinfile:
    path: "{{ apache_security_file }}"
    regexp: '^Header set {{ item.option }}'
    line: "Header set {{ item.option }} \"{{ item.value }}\""
    create: true
  notify:
    - Restart Apache
  loop:
    - { option: Strict-Transport-Security, value: max-age=31536000 }
    - { option: X-Content-Type-Options, value: nosniff }
    - { option: X-Frame-Options, value: SAMEORIGIN }
    - { option: Content-Security-Policy, value: "default-src 'self' https: http: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'" }
    - { option: X-Robots-Tag, value: noindex }

- name: Configure Apache Security Cookies
  when: ovd_add_security_headers
  tags: [ovd]
  lineinfile:
    path: "{{ apache_security_file }}"
    regexp: '^Header edit Set-Cookie'
    line: "Header edit Set-Cookie ^(.*)$ $1;Secure;SameSite=None;Partitioned;HttpOnly"
    create: true
  notify:
    - Restart Apache

- name: Configure Apache ServerTokens
  when: ovd_add_security_headers
  tags: [ovd]
  lineinfile:
    path: "{{ apache_security_file }}"
    regexp: '^ServerTokens'
    line: ServerTokens Prod
    create: true
  notify:
    - Restart Apache

- name: Configure Apache ServerSignature
  when: ovd_add_security_headers
  tags: [ovd]
  lineinfile:
    path: "{{ apache_security_file }}"
    regexp: '^ServerSignature'
    line: ServerSignature Off
    create: true
  notify:
    - Restart Apache
