# Copyright (C) 2018 Inuvika Inc.
# https://www.inuvika.com
# Author David PHAM-VAN <d.phamvan@inuvika.com> 2018
# Author Julien Langlois <julien@inuvika.com> 2018
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Verify "ovd_as_setup_type" parameter validity
  assert:
    that:
      - ovd_as_setup_type is defined
      - ovd_as_setup_type in ("exe", "msi")

- name: Enable audio service
  win_service:
    name: Audiosrv
    start_mode: auto
    state: started

- name: Wait for no scheduled tasks
  win_shell: Get-ScheduledTask | Where TaskPath -like "*TaskScheduler*"
  register: result
  until: result.stdout.find("Running") == -1
  retries: 30
  delay: 10
  changed_when: False

- name: Install RDS
  win_feature:
    name: "RDS-RD-Server"
    state: present
    restart: no
    include_sub_features: yes
    include_management_tools: yes
  register: install_rds

- name: Reboot after RDS install
  win_reboot:
  when: install_rds.reboot_required

- name: Configure RDS
  win_shell: |
    echo "nothing"

    $wmi_rds = (Get-WmiObject Win32_TerminalServiceSetting -Namespace root\cimv2\TerminalServices)
    if ($wmi_rds.AllowTsConnections -ne "1") {
      echo "Set AllowTsConnections to 1"
      $wmi_rds.SetAllowTsConnections(1,1);
    }

    $expected = {{ '1' if ovd_version_detected is version('2.6', '>=') else '0' }}

    $wmi_rdp = (Get-WmiObject -Class "Win32_TSGeneralSetting" -Namespace root\cimv2\TerminalServices -Filter "TerminalName='RDP-tcp'")

    if ($wmi_rdp.UserAuthenticationRequired -ne $expected) {
      echo "Set UserAuthenticationRequired to $expected"
      $wmi_rdp.SetUserAuthenticationRequired($expected);
    }
  register: result
  changed_when: result.stdout_lines[-1] != "nothing"

- name: Set RDP User Authentication Level
  win_regedit:
    section: Registry Values
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: UserAuthentication
    data: "{{ 1 if ovd_version_detected is version('2.6', '>=') else 0 }}"
    type: dword

- name: Set RDP Minimum Encryption Level
  win_regedit:
    section: Registry Values
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: MinEncryptionLevel
    data: "{{ 2 if ovd_version_detected is version('2.6', '>=') else 1 }}"
    type: dword

- name: Set RDP Security Layer
  win_regedit:
    section: Registry Values
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
    name: SecurityLayer
    data: "{{ 1 if ovd_version_detected is version('2.6', '>=') else 0 }}"
    type: dword

- set_fact:
    oas_setup_base: "{{ oas_setup_filename.result | splitext | first }}"

- name: Download OVD Windows Application Server
  win_get_url:
    url: '{{ ovd_repo }}/{{ oas_setup_base }}.{{ ovd_as_setup_type }}'
    dest: '%TEMP%\{{ oas_setup_base }}.{{ ovd_as_setup_type }}'
    force: no
  tags: [ovd, ovd-as]

- name: Extract the certificate from the Inuvika setup
  win_shell: "[System.IO.File]::WriteAllBytes('{{ oas_setup_base }}.cer', (Get-AuthenticodeSignature '{{ oas_setup_base }}.{{ ovd_as_setup_type }}').SignerCertificate.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert));"
  args:
    chdir: "{{ ansible_env.TEMP }}"
    creates: "{{ ansible_env.TEMP }}\\{{ oas_setup_base }}.cer"
  tags: [ovd, ovd-as]

- name: Install the Inuvika code-sign certificate as a trusted publisher
  win_certificate_store:
    path: "{{ ansible_env.TEMP }}\\{{ oas_setup_base }}.cer"
    store_name: TrustedPublisher
  tags: [ovd, ovd-as]

- name: "Install OVD Windows Application Server ({{ ovd_as_setup_type }})"
  win_package:
    path: "{{ ansible_env.TEMP }}\\{{ oas_setup_base }}.{{ ovd_as_setup_type }}"
    arguments: "{{ '/S' if ovd_as_setup_type == 'exe' else omit }}"
    product_id: "{{ 'Inuvika OVD Application Server' if ovd_as_setup_type == 'exe' else omit }}"
    state: present
  tags: [ovd, ovd-as]

- name: Configure Session Manager
  win_regedit:
    key: HKLM:\SOFTWARE\OVD\SlaveServer
    value: session_manager
    data: "{{ ovd_session_manager }}"
  tags: [ovd, ovd-as]
  notify:
    - Restart OVD Windows Application Server

- name: Configure Logs
  win_regedit:
    key: HKLM:\SOFTWARE\OVD\SlaveServer\log
    value: level
    data: "{{ ovd_slaveserver_log_levels }}"
  tags: [ovd, ovd-as]
  notify:
    - Restart OVD Windows Application Server

- name: Configure the Windows VFS
  win_lineinfile:
    path: '%ProgramData%\OVD\slaveserver\default.conf'
    regexp: '^union\s?='
    line: union = configuration, volatile, extravolatile, data
    insertafter: '^\[\s*main\s*\]'
  tags: [ovd, ovd-as]
  when: ovd_version_detected is version('2.6.1', '>=') and ovd_version_detected is version('2.6.2', '<=')

- name: Ensure OVD service is started
  win_service:
    name: OVD
    state: started
  tags: [ovd, ovd-as]

- name: Add a Scheduler to restart the Windows Font Cache Service
  win_scheduled_task:
    name: FontCache
    path: Inuvika
    actions:
    - path: cmd.exe
      arguments: /C "net stop FontCache && net start FontCache"
    triggers:
    - type: daily
      start_boundary: 3am
    description: "open command prompt"
    state: present
    user: SYSTEM
  ignore_errors: yes

- name: Apply "User Isolation" KB
  when: ovd_as_isolation is defined and ovd_as_isolation|bool==true
  block:
    - name: Apply "User Isolation" KB → Prevent OVDUsers to write in C:\
      win_acl:
        path: C:\
        user: "OVDUsers"
        type: deny
        rights: CreateDirectories, Write
        state: present
        propagation: None

    - name: Apply "User Isolation" KB → Prevent OVDUsers to list in C:\Users
      win_acl:
        path: C:\Users
        user: "OVDUsers"
        type: deny
        rights: ListDirectory
        state: present
        propagation: None

- name: Apply "Windows Security 2019" KB
  vars:
    winpath: 'C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy\SecHealthUI.exe'
  block:
    - name: Apply "Windows Security 2019" KB → Check that the Windows Security application exists
      win_stat:
        path: "{{ winpath }}"
      register: stat_file

    - name: Apply "Windows Security 2019" KB → Takeown Windows Security application
      when: stat_file.stat.exists == True
      win_owner:
        path: "{{ winpath }}"
        user: Administrator

    - name: Apply "Windows Security 2019" KB → Remove "Execute" ACL from Users
      when: stat_file.stat.exists == True
      win_acl:
        path: "{{ winpath }}"
        user: "Users"
        type: deny
        rights: ExecuteFile
        state: present

- name: Install NFS Client
  when: ovd_install_nfs is defined and ovd_install_nfs|bool==true
  win_feature:
    name: NFS-Client
    state: present
