# Copyright (C) 2018 Inuvika Inc.
# https://www.inuvika.com
# Author David PHAM-VAN <d.phamvan@inuvika.com> 2018
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Add the OS specific variables
  include_vars: "{{ item }}"
  loop:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
  failed_when: false
  tags: [ovd, ovd-wa]

- when:
    - ovd_version is version('3.1.90.1.sprint', '>=')
    - ansible_os_family != 'RedHat' or ansible_distribution_major_version != '7'
    - ovd_wa_www_config == 'auto'
  set_fact:
    ovd_wa_www_config: bridge

- when:
    - ovd_wa_www_config == 'auto'
  set_fact:
    ovd_wa_www_config: tomcat

- name: Check the "ovd_wa_www_config" setting value
  assert:
    that:
      - ovd_wa_www_config in ('tomcat', 'bridge')

- set_fact:
    ovd_wa_packages:
      - inuvika-ovd-web-access
      - inuvika-ovd-guacamole
      - inuvika-ovd-l10n
      - inuvika-ovd-web-access-ajaxplorer
      - inuvika-ovd-www-{{ ovd_www_config }}
      - inuvika-php-tank

- when: ovd_wa_www_config == 'bridge'
  set_fact: ovd_wa_packages="{{ ovd_wa_packages + [ 'inuvika-ovd-guacamole-bridge' ] }}"

- when: ovd_wa_www_config == 'tomcat'
  set_fact: ovd_wa_packages="{{ ovd_wa_packages + [ tomcat_service_name ] }}"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags: [ovd, ovd-wa]

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
  tags: [ovd, ovd-wa]

- name: Configure OVD Web Access
  template:
    src: config.inc.php
    dest: /etc/ovd/web-access/config.inc.php
    owner: "{{ apache_user_name }}"
    group: "{{ apache_group_name }}"
    mode: 0640
  tags: [ovd, ovd-wa]

- name: Check installed package
  package_facts:

- name: Ensure Tomcat is started
  when: ansible_facts.packages | select('match', '^%s$'|format(tomcat_service_name)) | list
  service:
    name: "{{ tomcat_service_name }}"
    state: started
    enabled: yes
  tags: [ovd, ovd-wa]

- name: Ensure Guacamole-bridge is started
  when: ansible_facts.packages | select("match", "inuvika-ovd-guacamole-bridge") | list
  service:
    name: guacamole-bridge
    state: started
    enabled: yes
  tags: [ovd, ovd-wa]

- name: Ensure Guacamole is started
  service:
    name: "{{ 'guacd' if ovd_version is version('3.0.99', '<') else 'guacamole' }}"
    state: started
    enabled: yes
  tags: [ovd, ovd-wa]

- name: Enable PHP-FPM
  when:
   - ovd_www_config == 'apache-fpm'
  service:
    name: '{{ fpm_service_name }}'
    state: started
    enabled: yes

- name: Enable Apache
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes
  ignore_errors: true
  tags: [ovd, ovd-wa]
