# Copyright (C) 2018 Inuvika Inc.
# https://www.inuvika.com
# Author David PHAM-VAN <d.phamvan@inuvika.com> 2018
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "SELinux : Set boolean"
  when: ansible_selinux.status != "disabled"
  block:
    - name: "SELinux : Configuration : Set boolean to allow php-fpm to execmem"
      seboolean:
        name: httpd_execmem
        state: yes
        persistent: yes

    - name: "SELinux : Configuration : Allow Apache to tcp connect"
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: "SELinux : Configuration 3.3"
      when: ovd_version is version('3.3', '>=')
      block:
        - name: "SELinux : Configuration 3.3 : Change context of /var/spool/ovd/html5/sessions"
          sefcontext:
            target: "/var/spool/ovd(/.*)?"
            setype: httpd_sys_rw_content_t

        - name: "SELinux : Configuration 3.3 : Deploy policy"
          block:
          - name: "SELinux : Configuration 3.3 : Copy policy to host"
            copy:
              src: ovd_webaccess.te
              dest: /tmp/ovd_webaccess.te

          - name: "SELinux : Configuration 3.3 : Create type file"
            command: checkmodule -M -m -o /tmp/ovd_webaccess.mod /tmp/ovd_webaccess.te

          - name: "SELinux : Configuration 3.3 : Package policy"
            command: semodule_package -o /tmp/ovd_webaccess.pp -m /tmp/ovd_webaccess.mod

          - name: "SELinux : Configuration 3.3 : Install policy"
            command: semodule -i /tmp/ovd_webaccess.pp

- name: Install OVD Web Access
  yum:
    name: "{{ ovd_wa_packages }}"
    state: latest
  tags: [ovd, ovd-wa]
